name: hugo-remote

on:
  push:
    branches:
      - main

env:
  REMOTE: iii-cutting-edge-tech-lab/iii-cutting-edge-tech-lab.github.io.git
  DEST: public
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🚀 Build and deploy
        uses: guan840912/hugo-remote@master
